author: AVM
name: linting
description: Tests the example supplied in the input. Needs checkout and Azure login prior.
inputs:
  github-token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:

    - name: terraform fmt check
      shell: bash
      run: |
        export TFENV_TERRAFORM_VERSION="1.9.2"
        docker run --rm -v $(pwd):/src -w /src -e TFENV_TERRAFORM_VERSION mcr.microsoft.com/azterraform make tffmtcheck

    - name: terraform validate
      shell: bash
      run: |
        export TFENV_TERRAFORM_VERSION="1.9.2"
        docker run --rm -v $(pwd):/src -w /src -e TFENV_TERRAFORM_VERSION mcr.microsoft.com/azterraform make tfvalidatecheck

    - name: terrafmt check
      shell: bash
      run: |
        export TFENV_TERRAFORM_VERSION="1.9.2"
        docker run --rm -v $(pwd):/src -w /src -e TFENV_TERRAFORM_VERSION mcr.microsoft.com/azterraform make terrafmtcheck

    - name: tflint
      shell: bash
      run: |
        export TFENV_TERRAFORM_VERSION="1.9.2"
        docker run --rm -v $(pwd):/src -w /src -e TFENV_TERRAFORM_VERSION mcr.microsoft.com/azterraform make tflint

    - name: tfsec
      shell: bash
      run: |
        echo "Bypass tfsec for now"